# Generated by Django 5.2.8 on 2025-11-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='noOfGuests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menutable',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menutable',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
