# Generated by Django 5.2.8 on 2025-11-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_bookingtable_noofguests_menutable_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='bookingDate',
            field=models.DateField(null=True),
        ),
    ]
