# Generated by Django 5.2.8 on 2025-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_bookingtable_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='noOfGuests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
