# Generated by Django 5.2.8 on 2025-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_bookingtable_noofguests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='noOfGuests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
